development: 
  cloud_name: "trevorsuter"
  api_key: "868838234985886"
  api_secret: "OwcZEOOyy7xtsr-JMAFXIHHagjE"
  secure: true

production:
  cloud_name: "trevorsuter"
  api_key: "868838234985886"
  api_secret: "OwcZEOOyy7xtsr-JMAFXIHHagjE"
  secure: true

test:
  cloud_name: "trevorsuter"
  api_key: "868838234985886"
  api_secret: "OwcZEOOyy7xtsr-JMAFXIHHagjE"
  secure: true
